### ISSUE TITLE
Beacon State Tracking Issue

### ISSUE THREAD

**Issue by itsdevbear** [berachain/beacon-kit#605]
- [ ] Spec BeaconStateObject
- [ ] Spec Optimial Storage for BeaconStateObject
- [ ] Spec the State Transitions around Beacon State
- [ ] Create abci.ValidatorUpdates from the result of the state transition.
